apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db-deployment
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: db
    spec:
      containers:
      - image: icodebetter/db_package
        name: db
        ports:
        - containerPort: 5432
        resources: {}
      restartPolicy: Always
status: {}