apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web-deployment
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
    spec:
      containers:
      - image: icodebetter/app_image
        name: web
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: OnFailure
status: {}